[package]
name = "rust-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.7.0"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
ureq = "2.7.1"
